version: '2.10.2'
services:
  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:3306'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8008:8000
    volumes:
      - .:/app
    depends_on:
      check-db-started:
        condition: service_completed_successfully
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    security_opt:
      - 'seccomp:unconfined'
    restart: always
    environment:
      MYSQL_DATABASE: queue_management
      MYSQL_USER: queue_management_admin
      MYSQL_PASSWORD: queue_management_password
      MYSQL_ROOT_PASSWORD: queue_management_password
    volumes:
      - db7:/var/lib/mysql
    ports:
      - 33099:3306


volumes: 
  db7:
