"""
Django settings for hdis_frontend project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from static_variables import *
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken',
    'doctor_administration',
    'appointment_booking',
    'consultation',
    'op_billing',
    'queue_management',
    'access_frontend',
    'patient_registration',
    'visit_management',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
   # "hdis_frontend.jwt_middleware.JWTMiddleware",
]

ROOT_URLCONF = "hdis_frontend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hdis_frontend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'frontend',
        'USER': 'frontend_admin',
        'PASSWORD': 'frontend_admin_password',
        'HOST': 'db',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = 'bootstrap5'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SESSION_COOKIE_AGE = 7200 # 3 minutes. "1209600(2 weeks)" by default

SESSION_SAVE_EVERY_REQUEST = True # "False" by default

HDIS_AUTH_SERVER="http://docker.for.mac.localhost:8080"
#HDIS_AUTH_SERVER="http://accessmanagement.openhdis.com:8080"

HDIS_ORG_MASTER="http://docker.for.mac.localhost:8081"
#HDIS_ORG_MASTER="http://facility.openhdis.com:8081"

#HDIS_PATIENT_MANAGEMENT="http://docker.for.mac.localhost:8003"
#HDIS_PATIENT_MANAGEMENT="http://patman.openhdis.com:8003"


HDIS_PATIENT_REGISTRATION="http://docker.for.mac.localhost:8002"
#HDIS_PATIENT_REGISTRATION="http://patreg.openhdis.com:8002"


HDIS_DOCTOR_ADMINISTRATION="http://docker.for.mac.localhost:8005"
#HDIS_DOCTOR_ADMINISTRATION="http://docadmin.openhdis.com:8005"

HDIS_SLOT_MASTER="http://docker.for.mac.localhost:8004"
#HDIS_SLOT_MASTER="http://slotmaster.openhdis.com:8004"


HDIS_APPOINTMENT_MANAGEMENT="http://docker.for.mac.localhost:8007"
#HDIS_APPOINTMENT_MANAGEMENT="http://appointment.openhdis.com:8007"

#SOAP
#HDIS_CONSULTATION_SUBJECTIVE="http://appointment.openhdis.com:8010"
#HDIS_CONSULTATION_OBJECTIVE="http://appointment.openhdis.com:8012"
#HDIS_CONSULTATION_ASSESSMENT="http://appointment.openhdis.com:8013"
#HDIS_CONSULTATION_PLAN="http://appointment.openhdis.com:8014"

HDIS_CONSULTATION_SUBJECTIVE="http://docker.for.mac.localhost:8010"
HDIS_CONSULTATION_OBJECTIVE="http://docker.for.mac.localhost:8012"
HDIS_CONSULTATION_ASSESSMENT="http://docker.for.mac.localhost:8013"
HDIS_CONSULTATION_PLAN="http://docker.for.mac.localhost:8014"

HDIS_VISIT_MANAGEMENT="http://docker.for.mac.localhost:8009"
#HDIS_VISIT_MANAGEMENT="http://visit.openhdis.com:8009"

HDIS_QUEUE_MANAGEMENT="http://docker.for.mac.localhost:8008"
#HDIS_QUEUE_MANAGEMENT="http://queue.openhdis.com:8009"