# Generated by Django 4.0.1 on 2023-04-22 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uniqueFacilityIdentificationNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('facilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('facilityServiceCode', models.CharField(blank=True, max_length=18, null=True)),
                ('departmentName', models.CharField(blank=True, max_length=99, null=True)),
                ('referralFacilityIdentificationNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('referralFacilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('referralFromFacilityIdentificationNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('referralFromFacilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('facilityGlobalUniqueIdentifier', models.BinaryField(blank=True, null=True)),
                ('facilitySpecialtyCode', models.IntegerField(default=999, validators=[django.core.validators.MaxValueValidator(999)])),
            ],
            options={
                'verbose_name_plural': 'Facility',
                'db_table': 'Facility',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProvidersPatientID', models.CharField(blank=True, max_length=18, null=True)),
                ('PatientName', models.CharField(blank=True, max_length=99, null=True)),
                ('PatientAge', models.CharField(default='999,99,99', max_length=9)),
                ('PatientDOB', models.DateTimeField(blank=True, null=True)),
                ('PatientGender', models.CharField(blank=True, max_length=12, null=True)),
                ('IdentityUnknownIndicator', models.IntegerField(default=0)),
                ('PatientAddress', models.CharField(blank=True, max_length=254, null=True)),
                ('PatientAddressType', models.CharField(blank=True, max_length=1, null=True)),
                ('patientLandlineNumber', models.CharField(blank=True, max_length=8, null=True)),
                ('patientMobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('patientEmailAddressURL', models.CharField(blank=True, max_length=254, null=True)),
                ('contactPersonName', models.CharField(blank=True, max_length=99, null=True)),
                ('contactType', models.CharField(blank=True, max_length=1, null=True)),
                ('contactRelationship', models.CharField(blank=True, max_length=10, null=True)),
                ('contactPersonLandLineNumber', models.CharField(blank=True, max_length=8, null=True)),
                ('ListofcontactPersonMobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('contactPersonEmailAddressURL', models.CharField(blank=True, max_length=254, null=True)),
                ('AmbulanceIdentificationNumber', models.CharField(blank=True, max_length=18, null=True)),
                ('AmbulanceType', models.CharField(blank=True, max_length=1, null=True)),
                ('AmbulanceOrignationSiteName', models.CharField(blank=True, max_length=50, null=True)),
                ('AmbulanceOriginationStartDateTime', models.DateTimeField(null=True)),
                ('AmbulanceReachLocationSiteName', models.CharField(blank=True, max_length=50, null=True)),
                ('AmbulanceReachLocationFinishedDateTime', models.DateTimeField(null=True)),
                ('RouteEvent', models.CharField(blank=True, max_length=50, null=True)),
                ('RouteEventDateTime', models.DateTimeField(null=True)),
                ('EnRouteDeliveryOutcome', models.CharField(blank=True, max_length=1, null=True)),
                ('DestinationRationale', models.CharField(blank=True, max_length=50, null=True)),
                ('AmbulanceParamedicID', models.CharField(blank=True, max_length=18, null=True)),
                ('AmbulanceDriverIdentificationNumber', models.CharField(blank=True, max_length=18, null=True)),
                ('patientStatus', models.CharField(blank=True, max_length=1, null=True)),
                ('patientArrivalDateTime', models.DateTimeField(null=True)),
                ('MLCStatus', models.CharField(blank=True, max_length=1, null=True)),
                ('FIRNumber', models.CharField(blank=True, max_length=18, null=True)),
                ('PatientClass', models.CharField(blank=True, max_length=1, null=True)),
                ('facilityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_registration.facility')),
            ],
            options={
                'verbose_name_plural': 'Patient',
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UniqueHealthIdentificationNumber', models.CharField(blank=True, max_length=18, null=True)),
                ('UniqueHealthIdentificationID', models.CharField(blank=True, max_length=254, null=True)),
                ('AlternateUniqueIdentificationNumberType', models.IntegerField(default=0)),
                ('AlternateUniqueIdentificationNumber', models.CharField(blank=True, max_length=18, null=True)),
                ('NationalityCode', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Person',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('InsuredCardID', models.CharField(blank=True, max_length=18, null=True)),
                ('TPACode', models.CharField(blank=True, max_length=18, null=True)),
                ('HealthPlanTypeCode', models.CharField(blank=True, max_length=18, null=True)),
                ('InsurancePolicyID', models.CharField(blank=True, max_length=18, null=True)),
                ('SourceOfPayment', models.CharField(blank=True, max_length=18, null=True)),
                ('SecondaryPolicyIndicator', models.CharField(blank=True, max_length=18, null=True)),
                ('ListofSecondaryPolicyID', models.CharField(blank=True, max_length=18, null=True)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_registration.patient')),
            ],
            options={
                'verbose_name_plural': 'Payment',
                'db_table': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='personId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_registration.person'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('EmployeeID', models.CharField(blank=True, max_length=18, null=True)),
                ('EmployerID', models.CharField(blank=True, max_length=18, null=True)),
                ('EmployeeTelephoneNumber', models.CharField(blank=True, max_length=8, null=True)),
                ('EmployeeMobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('EmployeeEmailAddress', models.CharField(blank=True, max_length=254, null=True)),
                ('EmployeeDesignationCode', models.CharField(blank=True, max_length=2, null=True)),
                ('EmployeeOrganizationName', models.CharField(blank=True, max_length=254, null=True)),
                ('PatientID', models.ManyToManyField(to='patient_registration.Patient')),
            ],
            options={
                'verbose_name_plural': 'Employee',
                'db_table': 'Employee',
            },
        ),
    ]
