# Generated by Django 4.0.1 on 2023-05-13 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientAddressDetail',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PatientAddress', models.CharField(blank=True, max_length=254, null=True)),
                ('PatientAddressType', models.CharField(blank=True, max_length=1, null=True)),
                ('patientLandlineNumber', models.CharField(blank=True, max_length=8, null=True)),
                ('patientMobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('patientEmailAddressURL', models.CharField(blank=True, max_length=254, null=True)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_registration.patient')),
            ],
            options={
                'verbose_name_plural': 'patientAddressDetail',
                'db_table': 'patientAddressDetail',
            },
        ),
    ]
