# Generated by Django 4.0.1 on 2023-05-12 00:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uniqueFacilityIdentificationNumber', models.UUIDField(default=uuid.uuid4)),
                ('facilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('facilityServiceCode', models.CharField(blank=True, max_length=18, null=True)),
                ('departmentName', models.CharField(blank=True, max_length=99, null=True)),
                ('referralFacilityIdentificationNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('referralFacilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('referralFromFacilityIdentificationNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('referralFromFacilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('facilityGlobalUniqueIdentifier', models.BinaryField(blank=True, null=True)),
                ('facilitySpecialtyCode', models.IntegerField(default=999, validators=[django.core.validators.MaxValueValidator(999)])),
            ],
            options={
                'verbose_name_plural': 'Facility',
                'db_table': 'Facility',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMobile', models.CharField(blank=True, max_length=64)),
                ('facilityId', models.ManyToManyField(to='access_management.Facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
