# Generated by Django 4.0.1 on 2023-04-23 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSessionSlots',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dayOfTheWeekSlotStartTime', models.CharField(default='08:00', max_length=5)),
                ('dayOfTheWeekSlotEndTime', models.CharField(default='22:00', max_length=5)),
                ('dayOfTheWeekSlotDuration', models.CharField(default='15', max_length=5)),
                ('dayOfTheWeekSlotStatus', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'AppointmentSessionSlots',
                'db_table': 'AppointmentSessionSlots',
            },
        ),
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('LocalHealthCareProviderNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('UniqueIndividualHealthCareProviderNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('UniqueFacilityIdentificationNumber', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProviderSchedule',
                'db_table': 'ProviderSchedule',
            },
        ),
        migrations.CreateModel(
            name='ProviderWeekDayDetails',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dayOfTheWeek', models.CharField(max_length=10)),
                ('dayOfTheWeekWorkingStatus', models.BooleanField(default=True)),
                ('providerWeekDayId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_details.providerschedule')),
            ],
            options={
                'verbose_name_plural': 'ProviderWeekDayDetails',
                'db_table': 'ProviderWeekDayDetails',
            },
        ),
        migrations.CreateModel(
            name='ProviderLeaveMaster',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaveDate', models.DateTimeField()),
                ('leaveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_details.providerschedule')),
                ('leaveSlotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_details.appointmentsessionslots')),
            ],
            options={
                'verbose_name_plural': 'ProviderLeaveMaster',
                'db_table': 'ProviderLeaveMaster',
            },
        ),
        migrations.AddField(
            model_name='appointmentsessionslots',
            name='slotId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_details.providerweekdaydetails'),
        ),
    ]
