# Generated by Django 4.0.1 on 2023-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facilityTypeService',
            field=models.CharField(default='Clinic', max_length=99),
        ),
    ]
