# Generated by Django 4.0.1 on 2023-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_management', '0002_facility_facilitytypeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_type', models.CharField(max_length=64)),
                ('Facility_User', models.CharField(max_length=64)),
                ('Facility_Permission', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'RoleAccess',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='members',
            name='memberPermissions',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
