version: '2.10.2'
services:
  check-db-started:
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:3306'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8014:8000
    volumes:
      - .:/app
    depends_on:
      check-db-started:
        condition: service_completed_successfully
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    platform: linux/arm64/v8
    security_opt:
      - 'seccomp:unconfined'
    restart: always
    environment:
      MYSQL_DATABASE: consultation_plan
      MYSQL_USER: consultation_plan_admin
      MYSQL_PASSWORD: consultation_plan_admin_password
      MYSQL_ROOT_PASSWORD: consultation_plan_admin_password
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./init_data:/docker-entrypoint-initdb.d/init_data
      - db14:/var/lib/mysql
    ports:
      - 33014:3306
    command:
      --secure-file-priv=docker-entrypoint-initdb.d


volumes:
  db14:
