# Generated by Django 4.0.1 on 2023-05-18 12:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UniqueIndividualHealthCareProviderNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('UniqueFacilityIdentificationNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('LocalHealthCareProviderNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('doctorName', models.CharField(blank=True, max_length=240, null=True)),
                ('doctorUserId', models.CharField(blank=True, max_length=240, null=True)),
                ('doctorSpeciality', models.CharField(blank=True, default='Physician', max_length=240)),
                ('profileStatus', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DoctorDetails',
                'db_table': 'DoctorDetails',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('PrimaryKey', models.UUIDField(primary_key=True, serialize=False)),
                ('uniqueFacilityIdentificationNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('facilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('facilityServiceCode', models.CharField(blank=True, max_length=18, null=True)),
                ('departmentName', models.CharField(blank=True, max_length=99, null=True)),
                ('referralFacilityIdentificationNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('referralFacilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('referralFromFacilityIdentificationNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('referralFromFacilityTypeCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('facilityGlobalUniqueIdentifier', models.BinaryField(blank=True, default=False, null=True)),
                ('facilitySpecialtyCode', models.IntegerField(default=999, validators=[django.core.validators.MaxValueValidator(999)])),
            ],
            options={
                'verbose_name_plural': 'Facility',
                'db_table': 'Facility',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uniqueIndividualHealthCareProviderNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('careProviderMobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('careProviderEmailAddress', models.CharField(blank=True, max_length=254, null=True)),
                ('careProviderName', models.CharField(blank=True, max_length=99, null=True)),
                ('healthServiceProviderRoleCode', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('healthServiceProviderRoleFreeText', models.CharField(blank=True, max_length=99, null=True)),
                ('healthServiceProviderType', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(99)])),
                ('facilityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_onboarding.facility')),
            ],
            options={
                'verbose_name_plural': 'Provider',
                'db_table': 'Provider',
            },
        ),
        migrations.CreateModel(
            name='FacilityDoctorFields',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctorType', models.BooleanField(default=True)),
                ('doctorRegistration', models.BooleanField(default=True)),
                ('doctorRegistrationCertificate', models.BooleanField(default=True)),
                ('doctorLanguage', models.BooleanField(default=False)),
                ('doctorCity', models.BooleanField(default=False)),
                ('doctorSpeciality', models.BooleanField(default=False)),
                ('doctorQualification', models.BooleanField(default=False)),
                ('doctorDescription', models.BooleanField(default=False)),
                ('doctorImage', models.BooleanField(default=False)),
                ('doctorSignatures', models.BooleanField(default=False)),
                ('doctorSchedule', models.BooleanField(default=False)),
                ('doctorBankDetails', models.BooleanField(default=False)),
                ('doctorLeaves', models.BooleanField(default=False)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_onboarding.facility')),
            ],
            options={
                'verbose_name_plural': 'FacilityDoctorFields',
                'db_table': 'FacilityDoctorFields',
            },
        ),
        migrations.CreateModel(
            name='DoctorQualificationDetails',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_degree', models.CharField(blank=True, max_length=150, null=True)),
                ('doctor_institute', models.CharField(blank=True, max_length=250, null=True)),
                ('doctor_qualification_year', models.CharField(blank=True, max_length=10, null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_onboarding.doctordetails')),
            ],
            options={
                'verbose_name_plural': 'DoctorQualificationDetails',
                'db_table': 'DoctorQualificationDetails',
            },
        ),
        migrations.CreateModel(
            name='DoctorPersonalDetails',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctorRegistrationNumber', models.CharField(blank=True, max_length=240, null=True)),
                ('doctorContactNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('languagesKnown', models.CharField(blank=True, max_length=240, null=True)),
                ('currentCity', models.CharField(blank=True, max_length=18, null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_onboarding.doctordetails')),
            ],
            options={
                'verbose_name_plural': 'DoctorPersonalDetails',
                'db_table': 'DoctorPersonalDetails',
            },
        ),
        migrations.CreateModel(
            name='DoctorDocuments',
            fields=[
                ('PrimaryKey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentType', models.CharField(blank=True, max_length=18, null=True)),
                ('documentFile', models.FileField(blank=True, null=True, upload_to='doctorDocuments/')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_onboarding.doctordetails')),
            ],
            options={
                'verbose_name_plural': 'DoctorDocuments',
                'db_table': 'DoctorDocuments',
            },
        ),
    ]
