version: '2.10.2'
services:
  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:3306'

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    restart: always
    depends_on:
      - db
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8003:8000
    volumes:
      - .:/app
    depends_on:
      check-db-started:
        condition: service_completed_successfully
  db:
    image: mysql
    security_opt:
      - 'seccomp:unconfined'
    restart: always
    environment:
      MYSQL_DATABASE: patient_management
      MYSQL_USER: patient_management_admin
      MYSQL_PASSWORD: patient_management_admin_password
      MYSQL_ROOT_PASSWORD: patient_management_admin_password
    volumes:
      - db4:/var/lib/mysql
    ports:
      - 33068:3306


volumes: 
  db4: