"""
Django settings for hdis_appointment_management project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from static_variables import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'host.docker.internal']
CORS_ORIGIN_ALLOW_ALL = True    #TODO: Debug only. Remove for Production

INSTALLED_APPS = [
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'oauth2_provider',
    'appointment_management',
]

AUTHENTICATION_BACKENDS = [
    'oauth2_provider.backends.OAuth2Backend',
    # Uncomment the following if you want to access the admin
    #'django.contrib.auth.backends.ModelBackend',
]

# The following OAuth2 configurations must be updated for each environment. Note that the Client Secret is unhashed.
HDIS_AUTH_SERVER="http://host.docker.internal:8080/api/v1"
OAUTH2_CLIENT_ID = 'd5BHnuCYgnDvgoEZEBpTOtKaLPTqnTb0VdE8Gl8e'
OAUTH2_CLIENT_SECRET = 'WyreSXtcdBZNhU9o18hy4qne0lXiKKKpG9sY4FH0Q1JDt1A3umocUT9gWzBfxsGRrmyxRNOdd7x84K8qBj1H0roxJ69Bjc5Yo0smPEfNU9bxrGg8pVlPOJDN1AbbtxUx'
OAUTH2_TOKEN_URL = HDIS_AUTH_SERVER + '/o/token/'
GET_PATIENT_BY_LFPID_URL = f"http://host.docker.internal:8003/api/v1/patients/lfpid/{{}}/"
GET_PROVIDER_BY_UHPN_URL = f"http://host.docker.internal:8005/api/v1/providers/uhpn/{{}}/"
#HDIS_ORG_MASTER="http://host.docker.internal:8081"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',    #Must appear before MessageMiddleware
    # AuthenticationMiddleware is NOT required for using django-oauth-toolkit but must appear before OAuth2TokenMiddleware.
    #'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hdis_appointment_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hdis_appointment_management.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'appointment_management',
        'USER': 'appointment_management_admin',
        'PASSWORD': 'appointment_management_password',
        'HOST': 'db',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
}

OAUTH2_PROVIDER = {
    'OAUTH2_VALIDATOR_CLASS': 'oauth2_provider.oauth2_validators.OAuth2Validator',    #Handles Access Token validation
    'RESOURCE_SERVER_INTROSPECTION_URL': HDIS_AUTH_SERVER + '/o/introspect/',
    #'RESOURCE_SERVER_AUTH_TOKEN': ''
    'RESOURCE_SERVER_INTROSPECTION_CREDENTIALS': ('d5BHnuCYgnDvgoEZEBpTOtKaLPTqnTb0VdE8Gl8e', 'WyreSXtcdBZNhU9o18hy4qne0lXiKKKpG9sY4FH0Q1JDt1A3umocUT9gWzBfxsGRrmyxRNOdd7x84K8qBj1H0roxJ69Bjc5Yo0smPEfNU9bxrGg8pVlPOJDN1AbbtxUx'),
}