version: '3.3'
services:

  check-db-started:
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:3306'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      check-db-started:
        condition: service_completed_successfully


  db:
    image: mysql
    platform: linux/arm64/v8
    security_opt:
      - 'seccomp:unconfined'
    restart: always
    environment:
      MYSQL_DATABASE: frontend
      MYSQL_USER: frontend_admin
      MYSQL_PASSWORD: frontend_admin_password
      MYSQL_ROOT_PASSWORD: frontend_admin_password
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./init_data:/docker-entrypoint-initdb.d/init_data
      - db16:/var/lib/mysql
    ports:
      - 33016:3306
    command:
      --secure-file-priv=docker-entrypoint-initdb.d


volumes:
  db16:
