# Generated by Django 4.0.1 on 2023-06-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitytype',
            fields=[
                ('facility_type_code', models.IntegerField(primary_key=True, serialize=False)),
                ('facility_type_description', models.CharField(max_length=64)),
                ('facility_short_type_name', models.CharField(max_length=4)),
                ('facility_type_internal', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'FacilityType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialityType',
            fields=[
                ('Medical_Specialty_Type_Code', models.IntegerField(primary_key=True, serialize=False)),
                ('Medical_Specialty_Type_Name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'SpecialityType',
                'managed': False,
            },
        ),
    ]
